<?php

/**
 * @file
 * Install hook to configure CKEditor5.
 */

/**
 * Install hook to configure CKEditor5.
 */
function iq_ckeditor5_install() {
  \Drupal::keyValue('system.schema')->set('iq_ckeditor5', 10000);
}

/**
 * Update hook to configure ck5 extensions.
 */
function iq_ckeditor5_update_10001() {
  $configurator = \Drupal::service('iq_ckeditor5.configurator');
  $configurator->configureExtensions();
}
